version: "3"
services:
  api:
    build:
      dockerfile: backend/Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - 3001:3001
  web:
    build:
      dockerfile: frontend/Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000